module core.EnvironmentManager;

/// Struct to keep used directorys organized
static struct EnvironmentManager {
    import std.experimental.logger : FileLogger;

    public static:
    /// Directory containing packageD data (e.g. repositorys)
    string dataDirectory;
    /// Directory containing packageD configuration files
    string configDirectory;
    /// Directory containing repository data
    string repositoryDirectory;
    /// Directory containing log 
    string logDirectory;
    /// Directory for temporary files generated by packageD
    string tmpDirectory;
    /// Sharedlogger
    FileLogger sharedLogger;

    /// Initialize Environment Manager
    void initialize() {
        version(Windows) {
            dataDirectory = setupFolder("dData", "C:\\.packageD\\data\\");
            configDirectory = setupFolder("dConfig", "C:\\.packageD\\config\\");
            repositoryDirectory = setupFolder(null, "C:\\.packageD\\data\\repositorys\\");
            logDirectory = setupFolder("dLog", "C:\\.packageD\\log\\");
            tmpDirectory = setupFolder("dTmp", "C:\\.packageD\\tmp\\");
        } else version(linux) { 
            dataDirectory = setupFolder("dData", "/var/packageD/");
            configDirectory = setupFolder("dConfig", "/etc/packageD/");
            repositoryDirectory = setupFolder(null, "/var/packageD/repositorys/");
            logDirectory = setupFolder("dLog", "/var/log/packageD/");
            tmpDirectory = setupFolder("dTmp", "/tmp/packageD/");
        } else {
            import std.stdio : writeln;
            import std.stdio : readln;
            writeln("OS NOT SUPPORTED YET!");
            writeln("Press any key to continue...");
            readln();
            exit(1);           
        }
        setupLogger();
        logInitialization();
    }

     
    string setupFolder(string env = null, string path = null) {
        import std.process : environment;
        if(env != null && environment.get(env)) {
            import std.string : format;
            version(Windows) {
                return format("%s\\", environment.get(env));
            } else version(linux) {
                return format("%s/", environment.get(env));
            }
        } else {
            import std.file : exists, mkdirRecurse;
            if(!exists(path)) 
                mkdirRecurse(path);
            return path;
        }
    }
    private:
    void setupLogger() {
        import std.datetime.systime : Clock;
        import std.string : format;
        import std.experimental.logger : log;
        sharedLogger = new FileLogger(format("%s%s.log",logDirectory, "LOG"));
    }
    void logInitialization() {
        import std.string : format;
        sharedLogger.log("[I]Logger initialized");
        sharedLogger.log("[I]EnvironmentManager initialized");
        sharedLogger.log(format("[D]data: %s", dataDirectory));
        sharedLogger.log(format("[D]config: %s", configDirectory));
        sharedLogger.log(format("[D]repository: %s", repositoryDirectory));
        sharedLogger.log(format("[D]log: %s", logDirectory));
        sharedLogger.log(format("[D]tmp: %s", tmpDirectory));
    }
}