module core.EnvironmentManager;

/// Struct to keep used directorys organized
static struct EnvironmentManager {
    import std.experimental.logger : FileLogger;

    public static:
    /// Directory containing packageD configuration files
    string configDirectory;
    /// Directory containing log 
    string logDirectory;
    /// Directory for temporary files generated by packageD
    string tmpDirectory;
    /// Sharedlogger
    FileLogger sharedLogger;

    /// Initialize Environment Manager
    void initialize() {
        version(Windows) {
            configDirectory = setupFolder("dConfig", "C:\\.packageD\\config\\");
            logDirectory = setupFolder("dLog", "C:\\.packageD\\log\\");
            tmpDirectory = setupFolder("dTmp", "C:\\.packageD\\tmp\\");
        } else version(linux) { 
            configDirectory = setupFolder("dConfig", "/etc/packageD/");
            logDirectory = setupFolder("dLog", "/var/log/packageD/");
            tmpDirectory = setupFolder("dTmp", "/tmp/packageD/");
        } else {
            import std.stdio : writeln;
            import std.stdio : readln;
            writeln("OS NOT SUPPORTED YET!");
            writeln("Press any key to continue...");
            readln();
            exit(1);           
        }
        setupLogger();
        logInitialization();
    }

    private: 
    string setupFolder(string env, string path) {
        import std.process : environment;
        if(environment.get(env)) {
            return environment.get(env);
        } else {
            import std.file : exists, mkdirRecurse;
            if(!exists(path)) 
                mkdirRecurse(path);
            return path;
        }
    }

    void setupLogger() {
        import std.datetime.systime : Clock;
        import std.string : format;
        import std.experimental.logger : log;
        sharedLogger = new FileLogger(format("%s%s.log",logDirectory, Clock.currTime.toUnixTime));
    }
    void logInitialization() {
        import std.string : format;
        sharedLogger.log("[I]Logger initialized");
        sharedLogger.log("[I]EnvironmentManager initialized");
        sharedLogger.log(format("[D]config: %s", configDirectory));
        sharedLogger.log(format("[D]log: %s", logDirectory));
        sharedLogger.log(format("[D]tmp: %s", tmpDirectory));
    }
}